### ISSUE TITLE
not showing up in obsidian plugins

### ISSUE THREAD

**Issue by ksdavidc** [daledesilva/obsidian_keep-import#1]
not showing up in obsidian community plugins
using Version 1.1.15 (Installer 0.14.15) on mac

**Comment by daledesilva** [comment]
Thanks for reaching out :)
I’m still waiting for the Obsidian team to approve it, so it won’t be listed yet.
However, you can install it manually.

download the realese directly from GitHub and then put the main,js, style.css, and manifest.json into their own folder in the obsidian plugins directory (which is in a hidden folder inside your vaults folder). Then just restart obsidian.

lemme know if you have an issues.

**Comment by daledesilva** [comment]
@ksdavidc it just went live in the marketplace if you haven’t seen it yet 🙂
