### ISSUE TITLE
Move code to Obsidian Importer?

### ISSUE THREAD

**Issue by dbarenholz** [daledesilva/obsidian_keep-import#10]
Hello! There's an official plugin, [Obsidian Importer](https://github.com/obsidianmd/obsidian-importer), which you may be interested contributing this to. Figured I'd bring it to your attention. See also [this issue](https://github.com/obsidianmd/obsidian-importer/issues/12) on that repo.

**Comment by kepano** [comment]
A bounty has been added to the Google Keep format on the official Importer repo

**Comment by daledesilva** [comment]
Thank you. I wasn’t aware of that. I’ve now applied.
