### ISSUE TITLE
Preserve indentation in checklists

### ISSUE THREAD

**Issue by Angush** [daledesilva/obsidian_keep-import#2]
Hey! Nice plugin; just imported all of my notes into Obsidian with nary a hitch.

Only issue I had was that checklist notes with indented items didn't have their indentation preserved after import.

For example, the following:
```
[ ] Item 1
    [ ] Item 1.1
[ ] Item 2
```

Was imported into Obsidian as:
```
[ ] Item 1
[ ] Item 1.1
[ ] Item 2
```

It wasn't much of an issue for me since I only had two or three notes where this applied, but could be an annoyance for others.

**Comment by daledesilva** [comment]
Thanks for creating an issue and me know! 
I’ll have a look soon and see if I can fix it up.

**Comment by Angush** [comment]
Actually, I just checked one of my files that had this issue. Seems the takeout doesn't include checklist indentation at all. I have a file that looks like this in Keep:

<img width="249" alt="image" src="https://user-images.githubusercontent.com/5266227/236184780-8389606d-2830-4282-89ac-4d3ef4c3a015.png">

But the JSON for it looks like this:

```json
{
  "listContent": [
    {
      "text": "And of course:",
      "isChecked": false
    },
    {
      "text": "Custom portfolio site",
      "isChecked": false
    },
    {
      "text": "Ascalon web interface",
      "isChecked": false
    }
  ]
}
```

The HTML export doesn't have any indentation either. Guess it's a no-go.

**Comment by daledesilva** [comment]
That's a shame. Thanks for checking. I'll close this issue and add a note in plugin that this isn't supported.
