### ISSUE TITLE
Import labels as tags (and possibly directories?)

### ISSUE THREAD

**Issue by Angush** [daledesilva/obsidian_keep-import#3]
Currently this plugin creates tags for the colours and archive/trash status, and leaves the Keep labels on the cutting room floor.

I imagine you've considered this already, but supporting labels would be a good addition.

--- 

Some other little label/tag-related ideas that I don't want to make an issue for:

1. Allow users to designate directories for specific labels (perhaps post-import, so we already have a list of available labels?), into which corresponding notes are placed. In the case of conflicts (eg. two labels on one note trying to put it in two places), the label-directory mapping could be a user-defined hierarchical order, or just use whichever comes first in each note's JSON labels array.
    - A basic version of this could just support Trashed and Archived folders. Having all of those dumped into the one folder alongside my actual saved notes made the import process require a bit more manual labour (though in retrospect I probably could have just re-imported my takeout three times with those types selectively enabled).
2. Option to escape tag-like text in the content of notes. A lot of my notes had references to Discord channels (eg. `#general`), and Obsidian automatically converts them into tags, so I had to go through all those notes to surround those channel references with back ticks and make them inline code snippets. Probably not a common issue, but it should be easy enough with a basic regex replace (eg. ```text.replace(/\b(#\S+)/, "`$1`")```)

**Comment by daledesilva** [comment]
Thanks @Angush !
I think I never used labels in keep and so never realised it was a thing. Could you attach a couple of example files?

In regard to folders for tags or labels, because of the ability for a note to have multiple tags or labels, I think however I solve that will be wrong for someone (not not being able to exit in multiple folders). My thinking is it’s best to leave them as tags and I would hope that selecting all files that relate to a tag and moving them manually should be easy in other tools or with obsidian itself afterward (but I’m not sure of that).
If that’s not possible,I’d probably more likely create a different plugin to enable that separately.

2. An option to escape tag like text might be an easy addition now you’ve provided that. I’ll have a look.

**Comment by Angush** [comment]
> If that’s not possible, I’d probably more likely create a different plugin to enable that separately.

Some generic plugin to organize notes into folders based on the tags? Yeah, that would make more sense.

> I think I never used labels in keep and so never realised it was a thing. Could you attach a couple of example files?

Sure! All files with labels seem to be structured the same, so here's an example: 

```json
{
  "color": "DEFAULT",
  "isTrashed": false,
  "isPinned": false,
  "isArchived": false,
  "textContent": "...",
  "title": "Alexis",
  "userEditedTimestampUsec": 1569773770150000,
  "createdTimestampUsec": 1569773597035000,
  "labels": [
    { "name": "Ideas" },
    { "name": "Writing" }
  ]
}
```

I believe the labels are always ordered alphabetically, not that it's relevant.

**Comment by tmaihoff** [comment]
@daledesilva Thanks for the great plugin! 
However, I'm also missing the labels during the import.
For me, this is a crucial feature and I would love to see it.

Best implementation for me is to just include it as Obsidian tags.

Any updates already?

**Comment by daledesilva** [comment]
> @daledesilva Thanks for the great plugin! However, I'm also missing the labels during the import. For me, this is a crucial feature and I would love to see it.
> 
> Best implementation for me is to just include it as Obsidian tags.
> 
> Any updates already?

Apologies, I've made the mistake of taking on all the improvements in one branch so rather than being able to quickly add labels it's slowed down and tied to the other updates. Hope to finish it in the next two weeks.

**Comment by interceptor** [comment]
This be very cool!

**Comment by daledesilva** [comment]
@Angush and @interceptor 
I've just updated the plugin to 1.1.0 so that it now supports labels.
Let me know if you have any issues :)

Other features and bug fixes described here:
[Release 1.1.0](https://github.com/daledesilva/obsidian_google-keep-import/releases/tag/1.1.0)
