### ISSUE TITLE
Import fails. Blank Screen. No Error Messages.

### ISSUE THREAD

**Issue by thesamim** [daledesilva/obsidian_keep-import#7]
Obsidian version: 1.3.5
obsidia_google-keep-import version: 1.0.0
No other plugins installed. Clean, newly created vault.

1. Start import
2. Drag all files (selecting files from disk, same behaviour), Note: Dragging HTML and JSon files.
3. First two files skipped. 
4. Second Two files imported
5. Freezes all Obsidian.

No errors in Console. No error messages. Just blank Obsidian screen. Can only kill Obsidian. 

Despite numbers: 4 keep notes imported. 

Tried only dragging JSon files in. Same results.

**Comment by daledesilva** [comment]
Now that you've updated (It should update properly now), do you still get this error?
I'm hoping not, but if you do, could you please try importing the files first few jsons to figure out which file is causing the crash. Then if you don't mind and you're happy to share it, zip the file and upload it so I can see what's going wrong.

Hopefully it's fixed though, and while it won't import that file (I suspect), it shouldn't freeze and should tell you which file's had an error.

**Comment by thesamim** [comment]
@daledesilva : Correctly updating now.

But: still freezing. I threw a console.log and found (at least) these three files to be problematic. I stopped testing after these three.
[suspect.zip](https://github.com/daledesilva/obsidian_google-keep-import/files/12088837/suspect.zip)

Google take out provides a json file and an hml file. It would appear that the html file versions of these three files does not cause issues....

Please let me know if there's anything else I can provide.

**Comment by thesamim** [comment]
Howdy,

 

Not Javascript, NPM or Github savy. 

 

Problem was with filename sanitization: There were several edge cases. I took a short cut and imported somebody else’s package. 

 

I forked the repository and did a pull request. 

 

I made a couple of other changes:

1.	If there is no title in the JSON, and the filename is going to be used as is, strip the “.json” extension from the name.
2.	Preserve the annotation in the keep note…. 

 

Obviously: feel free to do with this as you wish. This now works for me.

**Comment by thesamim** [comment]
Sorry, don’t know how to get rid of the readme.md commit from the pull request…

 

From: Sami Mikhail ***@***.***> 
Sent: Friday, July 21, 2023 6:23 PM
To: 'daledesilva/obsidian_google-keep-import' ***@***.***>; 'daledesilva/obsidian_google-keep-import' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [daledesilva/obsidian_google-keep-import] Import fails. Blank Screen. No Error Messages. (Issue #7)

 

Howdy,

 

Not Javascript, NPM or Github savy. 

 

Problem was with filename sanitization: There were several edge cases. I took a short cut and imported somebody else’s package. 

 

I forked the repository and did a pull request. 

 

I made a couple of other changes:

1.	If there is no title in the JSON, and the filename is going to be used as is, strip the “.json” extension from the name.
2.	Preserve the annotation in the keep note…. 

 

Obviously: feel free to do with this as you wish. This now works for me.

**Comment by daledesilva** [comment]
Thanks!
I added a few questions on your pull request here if you don't mind clarifying.
https://github.com/daledesilva/obsidian_google-keep-import/pull/9
