### ISSUE TITLE
All notes are skipped when uploaded

### ISSUE THREAD

**Issue by okfrasco** [daledesilva/obsidian_keep-import#8]
When i extract the Takeout Folder and upload all the json and html files they are are listed in _others_ instead of notes, and when I press _Import_ it says _"This file isn't supported by Obsidian and has been skipped"_

**Comment by daledesilva** [comment]
Thanks @okfrasco !
That's correct behaviour actually for the html files, they are not the core type of file that can be parsed by this plugin.
It should also tell you that you can change this behaviour in the settings.

In the settings you can turn on "import unsupported files" and that will reveal an option to import html files (and also describe why they're not turned on by default.

In regard to the JSON files, Are you sure they're being listed as "other" before you click import? They should be listed under "note" and I can't think of why they wouldn't be.
Perhaps try importing just jsons on their own and see what happens?

Also, if the json's aren't importing, it should list another error of some kind (Be sure to scroll down to see the whole error log).

Let me know what you see and take screenshots if possible or copy all the text from the error logs.

**Comment by okfrasco** [comment]
![image](https://github.com/daledesilva/obsidian_google-keep-import/assets/125671068/a5010bc1-6ae6-4d84-a0d8-eea235db8b1f)

I've downloaded the extension from Third Parties in Obsidian, downgraded from 1.3.5 to 1.1.16, trying files with different names but nothing seems to work.

**Comment by daledesilva** [comment]
Thanks @okfrasco !
That's expected behaviour with the html file, however, it's unexpected with the json.

I also just updated the plugin to 1.1.0 and made these error logs more descriptive (plus other features).
Could you please update the plugin to that and try again.

If the problem still persists (or the error log doesn't provide clarity), if you don't mind, please zip that json file and upload it here so I can test it.

Lastly, what's your operating system? Windows, Mac, Linux, Android, iOS?

**Comment by okfrasco** [comment]
It says that it isn't a Google Keep JSON

This is the JSON file Format

{"color":"DEFAULT","isTrashed":false,"isPinned":false,"isArchived":false,"textContent":"Text","title":"","userEditedTimestampUsec":1689945960682000,"createdTimestampUsec":1689943814665000,"labels":[{"name":"Label1"},{"name":"Label2"}]}

**Comment by daledesilva** [comment]
Thanks @okfrasco 
Looks valid to me. Did you try updating the plugin?

**Comment by okfrasco** [comment]
Yes, I'm using it now with version 1.1.16 and it doesn't work

**Comment by okfrasco** [comment]
Can you send me a JSON you know it works?

**Comment by daledesilva** [comment]
From the version number you mentioned, it appears you may have checked your version of Obsidian, but not the verson of this plugin.

Please go to settings / Community Plugins / Check for updates, and then update the Google Keep Importer plugin.
I just released another minor update, so you should still see an update to run even if you did it before.

Here's a zip file of several notes that work for you to try.
[Test Notes.zip](https://github.com/daledesilva/obsidian_google-keep-import/files/12206311/Test.Notes.zip)
